export const AUTHENTICATION_LOGIN_REQUEST = 'AUTHENTICATION_LOGIN_REQUEST'
export const AUTHENTICATION_LOGIN_SUCCESSFUL = 'AUTHENTICATION_LOGIN_SUCCESSFUL'
export const AUTHENTICATION_LOGIN_ERROR = 'AUTHENTICATION_LOGIN_ERROR'

export const SIGNUP_AUTHENTICATE_REQUEST = 'SIGNUP_AUTHENTICATE_REQUEST'
export const SIGNUP_AUTHENTICATE_SUCCESSFUL = 'SIGNUP_AUTHENTICATE_SUCCESSFUL'
export const SIGNUP_AUTHENTICATE_ERROR = 'SIGNUP_AUTHENTICATE_ERROR'