export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESSFUL = 'USER_SIGNUP_SUCCESSFUL'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'