export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESSFUL = 'USER_SIGNUP_SUCCESSFUL'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'

export const CREDIT_SAVE_REQUEST = 'CREDIT_SAVE_REQUEST'
export const CREDIT_SAVE_SUCCESSFUL = 'CREDIT_SAVE_SUCCESSFUL'
export const CREDIT_SAVE_ERROR = 'CREDIT_SAVE_ERROR'

export const CREDIT_GET_REQUEST = 'CREDIT_GET_REQUEST'
export const CREDIT_GET_SUCCESSFUL = 'CREDIT_GET_SUCCESSFUL'
export const CREDIT_GET_ERROR = 'CREDIT_GET_ERROR'